#!/bin/sh

case "$1" in
  start)
    scull_load || exit 1
    module_load faulty || exit 1 
    modprobe hello || exit 1
    ;;

  stop)
    scull_unload
    module_unload faulty
    rmmod hello 2>/dev/null
    ;; 
  *)
    echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac

exit 0
